behnaz/newfundmethod-nganluong
binary-com/deriv-static-content pull request #135
Opened 2020-09-10 09:18 UTC by behnaz-fs

2020-09-10 16:51 UTC, sash-binary requested changes

2020-09-10 16:51 UTC, sash-binary commented on email/templates/marketing/ngan-fundmethod.html
> +                                <a class="button-secondary" href="https://deriv.com/payment-methods/nganluong-payment-method.pdf" style="mso-hide:all;"><span>Download PDF</span></a>
remove span from link 
```suggestion
                                <a class="button-secondary" href="https://deriv.com/payment-methods/nganluong-payment-method.pdf" style="mso-hide:all;">Download PDF</a>
```

2020-09-10 16:51 UTC, sash-binary commented on email/templates/marketing/ngan-fundmethod.html
> +            /* http://meyerweb.com/eric/tools/css/reset/
no need for html5 reset

2020-09-13 03:37 UTC, behnaz-fs commented on email/templates/marketing/ngan-fundmethod.html
> +                                <a class="button-secondary" href="https://deriv.com/payment-methods/nganluong-payment-method.pdf" style="mso-hide:all;"><span>Download PDF</span></a>
Done

2020-09-13 03:46 UTC, behnaz-fs commented on email/templates/marketing/ngan-fundmethod.html
> +            /* http://meyerweb.com/eric/tools/css/reset/
css reset helps to remove default browsers setting e.g padding/margin, then set padding/margin to be sure have same result in all browsers, right?

2020-09-13 06:15 UTC, sash-binary commented on email/templates/marketing/ngan-fundmethod.html
> +            /* http://meyerweb.com/eric/tools/css/reset/
email is not shown in browser, so no need

2020-09-13 13:53 UTC, behnaz-fs commented on email/templates/marketing/ngan-fundmethod.html
> +            /* http://meyerweb.com/eric/tools/css/reset/
it helps to have same setting, so help to keep consistency

2020-09-14 06:06 UTC, merged