Amir/feq 692/convert circle ci config to GitHub workflow
binary-com/deriv-static-content pull request #1392
Opened 2023-09-19 07:29 UTC by amir-deriv

2023-09-19 07:44 UTC, ali-hosseini-deriv commented on .github/actions/publish_to_pages_production/action.yml
> +    shell: bash
fix the EOF error please

2023-09-19 07:44 UTC, ali-hosseini-deriv commented on .github/actions/send_slack_notifications/action.yml
> +    shell: bash
EOF

2023-09-19 07:44 UTC, ali-hosseini-deriv commented on .github/actions/versioning/action.yml
> +    shell: bash
EOF

2023-09-19 07:44 UTC, ali-hosseini-deriv commented on .gitignore
> +.cache/
why we need these?

2023-09-19 07:44 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +    if: # GitHub does not currently support regular expressions inside if conditions
I dont think that we need this.

2023-09-19 07:44 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +    - master
does it have to be run on merge to master?
dont we use any tag push here?

2023-09-19 07:44 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +    - uses: "./.github/actions/publish_to_pages_production"
you have to pass the secrets and vars to composite actions

2023-09-19 07:44 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +    - uses: "./.github/actions/send_slack_notifications"
please pass the needed secrets and vars to it.

2023-09-19 07:44 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +      image: node:18.4.0
what about 18.16?

2023-09-19 09:24 UTC, amir-deriv commented on .gitignore
> +.cache/
After running `gh` `action-importer` I get the `.cache` directory as output, which has 100+ changes, so I have to put `.cache` here

2023-09-19 09:31 UTC, amir-deriv commented on .github/workflows/release_production.yml
> +    - master
by looking at the previous implementation, I found nothing related to tag in this repository

2023-09-22 11:48 UTC, ali-hosseini-deriv commented on .github/actions/publish_to_pages_production/action.yml
> +    required: true
```suggestion
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare Account ID'
    required: true
```

2023-09-22 11:48 UTC, ali-hosseini-deriv commented on .github/actions/publish_to_pages_production/action.yml
> +    CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
```suggestion
    CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}

```

2023-09-22 11:48 UTC, ali-hosseini-deriv commented on .github/actions/versioning/action.yml
> +
Please fix EOL error

2023-09-22 11:48 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
```suggestion
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets. CLOUDFLARE_ACCOUNT_ID }}

```

2023-10-09 06:01 UTC, ali-hosseini-deriv requested changes

2023-10-09 06:01 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +      - uses: "./.github/actions/send_slack_notifications"
```suggestion
      - uses: "./.github/actions/send_slack_notifications"
      - name: Extract version
      run: echo "VERSION=${{ echo cat public/version }}"
```

2023-10-10 10:44 UTC, amir-deriv commented on .github/workflows/release_production.yml
> +      - uses: "./.github/actions/send_slack_notifications"
<img width="623" alt="image" src="https://github.com/binary-com/deriv-static-content/assets/129206554/eb26f318-1be9-4cc7-a1d0-0bd9f9927015">

I did it this way, is it okay ?

2023-10-10 10:45 UTC, amir-deriv commented on .github/workflows/release_production.yml
> +      - uses: "./.github/actions/send_slack_notifications"
by placing your suggestion, It is giving me syntax error

2023-10-10 10:46 UTC, amir-deriv commented on .github/actions/send_slack_notifications/action.yml
> +  CLOUDFLARE_ACCOUNT_ID:
please check now

2023-10-10 10:46 UTC, amir-deriv commented on .github/actions/send_slack_notifications/action.yml
> +          $SLACK_WEBHOOK_URL
please check now

2023-10-10 10:46 UTC, amir-deriv commented on .github/actions/send_slack_notifications/action.yml
> +          $SLACK_WEBHOOK_URL
please check now

2023-10-10 10:46 UTC, amir-deriv commented on .github/workflows/release_production.yml
> +          version: $(echo cat public/version | bash)
please check now

2023-10-12 05:29 UTC, ali-hosseini-deriv commented on .github/actions/publish_to_pages_production/action.yml
> +    required: true
@amir-deriv you also need the   `CLOUDFLARE_ACCOUNT_ID` in this action.
this is mandatory for wrangler

2023-10-12 05:29 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +      - uses: "./.github/actions/send_slack_notifications"
my bad, that was wrong.
Instead of having the step for it. you can directly call it in your `with` property.
let's have a call regarding this

2023-10-13 06:31 UTC, ali-hosseini-deriv commented on .github/workflows/release_production.yml
> +          CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
```suggestion
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
```

2023-10-13 07:09 UTC, ali-hosseini-deriv approved these changes

2023-10-16 05:52 UTC, habib-deriv commented on .github/actions/publish_to_pages_production/action.yml
> +      npx wrangler pages publish . --project-name=deriv-static-content-pages --branch=main
```suggestion
      npx wrangler pages deploy . --project-name=deriv-static-content-pages --branch=main
```

2023-10-16 07:00 UTC, ali-hosseini-deriv commented on .github/actions/publish_to_pages_production/action.yml
> +      npx wrangler pages publish . --project-name=deriv-static-content-pages --branch=main
good catch @habib-deriv 
@amir-deriv I think we better to use a specific version of wrangler too.
You can simply install it before using it. 
```suggestion
      npm i wrangler@3.1.0
      npx wrangler pages deploy . --project-name=deriv-static-content-pages --branch=main
```

2023-10-19 05:59 UTC, habib-deriv submitted a review, later dismissed
LGTM

2023-10-19 06:41 UTC, ali-hosseini-deriv approved these changes

2023-10-19 06:43 UTC, habib-deriv approved these changes
LGTM

2023-10-19 06:43 UTC, merged