khalid/ Add new utm fields
binary-com/deriv-static-content pull request #276
Opened 2021-06-16 10:23 UTC by Khalidxx

- Added `utm_ad_id`, `utm_adgroup_id`, and `utm_campaign_id`
- Refactored code

2021-06-16 10:38 UTC, mustofa-binary requested changes

2021-06-16 10:38 UTC, mustofa-binary commented on scripts/cookie.js
> +    console.log(utm_data)
nit: console 😅

2021-06-16 10:38 UTC, mustofa-binary commented on scripts/cookie.js
> +        utm_data[field] = searchParams.get(field).replace(/[^a-zA-Z0-9\s\-\.\_]/gi, '').substring(0, 100);
😱 isn't this will replace all allowed characters to null

2021-06-16 10:38 UTC, mustofa-binary commented on scripts/cookie.js
> +  const has_all_params = required_fields.every((field) => searchParams.has(field))
pleae help to check cross browser for `every` 🙏

2021-06-16 10:39 UTC, Khalidxx commented on scripts/cookie.js
> +    console.log(utm_data)
Oh shit, sorry 😅

2021-06-16 10:42 UTC, Khalidxx commented on scripts/cookie.js
> +        utm_data[field] = searchParams.get(field).replace(/[^a-zA-Z0-9\s\-\.\_]/gi, '').substring(0, 100);
Oh no, the `^` symbol will select for characters that are not according to the regex. It's actually the same as the binary-static check cause that looked just like the one in the API 😄

2021-06-16 10:42 UTC, Khalidxx commented on scripts/cookie.js
> +  const has_all_params = required_fields.every((field) => searchParams.has(field))
Okay checking now

2021-06-16 11:06 UTC, Khalidxx commented on scripts/cookie.js
> +  const has_all_params = required_fields.every((field) => searchParams.has(field))
Yess, it works for all modern browsers. Here's the (MDN reference)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every] as well

2021-06-17 05:15 UTC, mustofa-binary approved these changes

2021-06-17 06:34 UTC, sean-binary approved these changes

2021-06-17 07:28 UTC, merged