khalid/utm-source defaults and priorities
binary-com/deriv-static-content pull request #292
Opened 2021-07-07 06:28 UTC by Khalidxx

- Using `document.referrer` as the default value for `utm_source`
- Priority is set for URL params containing new UTM tags to overwrite old UTM tags
- Hands-off approach, no hard checks for correct combination of UTM tags. Whichever tags received will be saved

2021-07-07 12:17 UTC, arome-binary submitted a review, later dismissed
LGTM

2021-07-08 05:53 UTC, sean-binary approved these changes
LGTM

2021-07-22 02:34 UTC, sean-binary approved these changes

2021-07-28 18:10 UTC, mustofa-binary requested changes

2021-07-28 18:10 UTC, mustofa-binary commented on scripts/cookie.js
> +  const has_all_params = required_fields.every((field) => searchParams.has(field) && Object.keys(current_utm_data).includes(field))
includes uses heavy computation (O(n)), in total TC will be O(n^2) for this statement, I am sure there is a way to reduce the time complexity here 😉

2021-07-28 18:10 UTC, mustofa-binary commented on scripts/cookie.js
> +    if (new_utm_data.utm_medium.includes("ppc") && !current_utm_data.utm_medium.includes("aff")) return true; // 2. PPC tags
if it is an order, you may use if , else if

2021-07-28 18:10 UTC, mustofa-binary commented on scripts/cookie.js
> +      utm_source: document.referrer ? document.referrer : null,
```suggestion
      utm_source: document.referrer,
```

2021-07-28 18:10 UTC, mustofa-binary commented on scripts/cookie.js
> +      utm_data[field] = searchParams.get(field).replace(/[^a-zA-Z0-9\s\-\.\_]/gi, '').substring(0, 100);
maybe can give context/comment on what this statement is doing here 🙏

2021-07-29 07:59 UTC, khalid-deriv commented on scripts/cookie.js
> +      utm_source: document.referrer ? document.referrer : null,
If there is no referrer, `document.referrer` will return an empty string "". On BI side in bigquery tables it will just appear as empty field that's why added null

2021-07-29 08:00 UTC, khalid-deriv commented on scripts/cookie.js
> +  const has_all_params = required_fields.every((field) => searchParams.has(field) && Object.keys(current_utm_data).includes(field))
Actually no reason both are the same 😂

2021-07-29 08:35 UTC, khalid-deriv commented on scripts/cookie.js
> +  const has_all_params = required_fields.every((field) => searchParams.has(field) && Object.keys(current_utm_data).includes(field))
Hmmm 🤔

2021-07-29 09:05 UTC, mustofa-binary approved these changes

2021-07-29 09:06 UTC, merged